permalink: /:year/:month/:day/:title 

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
pygments: true


title : SUNY Fredonia
tagline: SUNY Fredonia educates, challenges, and inspires students to become skilled, connected, creative, and responsible global citizens and professionals. The university enriches the world through scholarship, artistic expression, community engagement, and entrepreneurship.
author :
  name : SUNY Fredonia
  email : webmaster@fredonia.edu
  github : sunyfredonia
  twitter : sunyfredonia


production_url : http://sunyfredonia.github.io/homepage

base_url : http://sunyfredonia.github.io/homepage

# All Jekyll-Bootstrap specific configurations are namespaced into this hash
#
JB :
  version : 0.3.0

  # All links will be namespaced by BASE_PATH if defined.
  # Links in your website should always be prefixed with {{BASE_PATH}}
  # however this value will be dynamically changed depending on your deployment situation.
  #
  # CNAME (http://yourcustomdomain.com)
  #   DO NOT SET BASE_PATH 
  #   (urls will be prefixed with "/" and work relatively)
  #
  # GitHub Pages (http://username.github.io)
  #   DO NOT SET BASE_PATH 
  #   (urls will be prefixed with "/" and work relatively)
comments :
    provider : disqus
    disqus :
      short_name : 
   
  # Settings for analytics helper
  # Set 'provider' to the analytics provider you want to use.
  # Set 'provider' to false to turn analytics off globally.
  #        
  analytics :
    provider : google 
    google : 
        tracking_id : 'UA-3356362-16'

  
  # Settings for all other include helpers can be defined by creating 
  # a hash with key named for the given helper. ex:
  #
  #   pages_list :
  #     provider : "custom"   
  #
  # Setting any helper's provider to 'custom' will bypass the helper code
  # and include your custom code. Your custom file must be defined at:
  #   ./_includes/custom/[HELPER]
  # where [HELPER] is the name of the helper you are overriding.
  

authors:
  ngunner:
    name: Nicholas Gunner
    display_name: Nicholas Gunner
    bio: New Media Manager at SUNY Fredonia
    gravatar: http://www.gravatar.com/avatar/a85d870dce3cc177b6b0016a1ef4c200.png
    email: gunner@fredonia.edu
    web: http://www.nicholasgunner.com
    twitter: nicholas_gunner
    github: ngunner
  jwoolson:
    name: Jonathan Woolson
    display_name: Jonathan Woolson
    bio: Webmaster at SUNY Fredonia
    gravatar: 
    email: 
    web: 
    twitter: 
    github: 
  awasiura:
    name: Andrea Wasiura
    display_name: Andrea Wasiura
    bio: Web administrator at SUNY Fredonia
    gravatar: 
    email: 
    web: 
    twitter: 
    github:   

  
timezone : America/New_York